### ISSUE TITLE
Timezone Error on run of fetchrange3.pl

### ISSUE THREAD

**Issue by KevWal** [glidernet/ogn-range#1]
Hi

On running fetchrange3.pl I get an error:

DBD::mysql::db do failed: Unknown or incorrect time zone: 'GMT'.

The issue seems to be:

https://mariadb.com/kb/en/mariadb/documentation/internationalization-and-localization/time-zones/

"By default, the mysql time zone tables are created, but not populated. It is usually preferable for the system to handle the time zone, but you can populate the mysql time zone tables using the mysql_tzinfo_to_sql utility"

Running:

mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql -p

fixed it fine.

Thanks
Kevin

**Comment by acasadoalonso** [comment]
Changed to: time zone = +00:00 and fixed the problem

**Comment by acasadoalonso** [comment]
Changed to be +00:00 in the DB call
