### ISSUE TITLE
Use of uninitialized value $cpu

### ISSUE THREAD

**Issue by KevWal** [glidernet/ogn-range#2]
Hi Mel

Apologies, you may be aware of these, but in running your great range tool I see a few issues coming up.  I will log them as issues here, and hopefully I can propose answers to solve them too.

This one looks to be an issue with the new PilotAware OGN-R stations not sending across CPU values:

location beacon PWEGBKE>APRS,TCPIP*,qAC,GLIDERN4:/215651h5219.36NI00042.37W&/A=000302

details beacon PWEGBKE>APRS,TCPIP*,qAC,GLIDERN4:>220142h v20180119 OGN-R/PilotAware
::              PWEGBKE: ppm -99.0/-99.0 db [PWEGBKE>APRS,TCPIP*,qAC,GLIDERN4:>220142h v20180119 OGN-R/PilotAware Use of uninitialized value $cpu in numeric lt (<) at /home/ognrange/ogn-range/bin/fetchrange3.pl line 661.
Use of uninitialized value $cpu in concatenation (.) or string at /home/ognrange/ogn-range/bin/fetchrange3.pl line 663.
PWEGBKE: LOWCPU & noppm (flagged 18 times)PWEGBKE>APRS,TCPIP*,qAC,GLIDERN4:>220142h v20180119 OGN-R/PilotAware>>cpu  0 ppm, 0 db

**Comment by KevWal** [comment]
Whilst it doesn't fix the overall PilotAware issue, to fix the Perl warnings this change looks like a sensible one?

Changing
my $cpu = undef; my $ppm = 0; my $dbadj = 0; my $temp = -273;
to:
my $cpu = 0; my $ppm = 0; my $dbadj = 0; my $temp = -273;

**Comment by acasadoalonso** [comment]
Fixed on the last PR
