### ISSUE TITLE
DBD::mysql::st execute failed: Out of range value for column 'temp'

### ISSUE THREAD

**Issue by KevWal** [glidernet/ogn-range#3]
Occasionally we get a big list of errors like these:

DBD::mysql::st execute failed: Out of range value for column 'temp' at row 1 at /home/ognrange/ogn-range/bin/fetchrange3.pl line 525.
DBD::mysql::st execute failed: Out of range value for column 'temp' at row 1 at /home/ognrange/ogn-range/bin/fetchrange3.pl line 526.
DBD::mysql::st execute failed: Out of range value for column 'temp' at row 1 at /home/ognrange/ogn-range/bin/fetchrange3.pl line 525.
DBD::mysql::st execute failed: Out of range value for column 'temp' at row 1 at /home/ognrange/ogn-range/bin/fetchrange3.pl line 526.
DBD::mysql::st execute failed: Out of range value for column 'temp' at row 1 at /home/ognrange/ogn-range/bin/fetchrange3.pl line 525.

**Comment by acasadoalonso** [comment]
Fixed on the last PR
