### ISSUE TITLE
Wildcard no longer working

### ISSUE THREAD

**Issue by eroom1966** [glidernet/ogn-range#5]
Hi All

Great work in getting this up and running again from the initial work done by Mel.

One small request, Mel had made an enhancement to use '%' as a globbing character in station names, this allowed to see an overlap of multiple stations, in particular for the PilotAware detection we would select 

'PW%'

this would provide all PW prefixed stations, these seems to have broken, any chance of re-instating ?

Thx
Lee

**Comment by nbonniere** [comment]
Didn't see any sign of that in the web viewer code.  Perhaps it is at the database level, not at the web viewer level ?

**Comment by eroom1966** [comment]
It’s possible, I am copying Mel in the hope she can clarify.

Mel, can you shed some light on this ?

Thx 
Lee

**Comment by eroom1966** [comment]
Yes, I think it is in the database code. I will have a look and see why it isn’t working. My recollection was that not all map types supported wildcards. 

Mel

**Comment by nbonniere** [comment]
It is not working because I forced a match between the stationName and the stationList to fix a mixedCase bug which wouldn’t jump to station typed in, and not get the data for a mixed case station name.

If you allow widcards in the station name, how can you jump to the correct location ?   Pick the first match and jump to that one ? or the average coords of all matches ?  or what ?   This can quickly break things if not thought out properly.  Please no quick fix !

Nick


--------------------------------------------------------------------------------

**Comment by eroom1966** [comment]
@nbonniere 
I understand your concerns, my original request to Mel was that we wanted to be able to generate consolidated overlays of multiple ground stations, this would allow us to easily visualize 'the holes', this was then used to prioritize where to place the next set of stations

I think I suggested a similar method to Linux globbing using '*' and '?', Mel investigated and provided the '%' character to act as a globbing character. For PilotAware, all stations are prefixed PW, hence this worked perfectly to allow us to ask for a display of 'PW%' - then we could easily see the holes.

Thx
Lee

**Comment by nbonniere** [comment]
I have made a change for a special case to allow for the ‘%’ wildcard character.

Try it and see if it works as expected.

http://withonestone.com/OGNrangeNew/index.html#pw%,max,recent,52.00408_-1.25764,8,#00990000:#009900ff,circles;

Nick


--------------------------------------------------------------------------------

**Comment by eroom1966** [comment]
@nbonniere 
Hi Nick
Perfect !
Exactly what I was hoping for, if this can be pushed to the ognrange
Thx
Lee

**Comment by eroom1966** [comment]
Closing
