### ISSUE TITLE
Add "station" query param to "stations2-filtered.pl"

### ISSUE THREAD

**Issue by saugs** [glidernet/ogn-range#9]
Hi,

Thanks for your great job on this project.
I'm using the "stations2-filtered.pl" to query latest status of receivers, but for a specific receiver only and so I'm generating useless traffic.

Might be good to add a "station" query parameter that returns status only for specified station.

Kindly,
Seb.

**Comment by acasadoalonso** [comment]
Seb,
The OGN is a community project, feel free to prepare and submit a PR, we will test it and make it available to everyone
Cheers

Enviado desde mi iPhone.
AC/.

**Comment by saugs** [comment]
You're right.

Tried it but got "403 permission denied" while trying to push my new branch, before creating a PR.
Am I supposed to have the rights on the repo?

Attached the modified file, just in case:
[stations2-filtered.pl.txt](https://github.com/glidernet/ogn-range/files/4925669/stations2-filtered.pl.txt)

**Comment by acasadoalonso** [comment]
You need to fork create your repo, update the code and submit the PR 

Enviado desde mi iPhone.
AC/.

**Comment by acasadoalonso** [comment]
PR applied 
I will move the code over ognrange.glidernet.org over the weeken
